apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: ganesh-devops-bootcamp
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-creds
            key: secret-manager.json
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-db-password-sync
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: my-secure-db-secret # The name of the native K8s secret that gets created
  data:
  - secretKey: password
    remoteRef:
      key: prod-db-password
