apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubecost.github.io/cost-analyzer/'
    targetRevision: 2.3.2
    chart: cost-analyzer
    helm:
      values: |
        kubecostToken: "a3ViZWNvc3RAdGVzdC5jb20=xm343yadf98"
        global:
          prometheus:
            enabled: false
            fqdn: "http://observability-stack-kube-p-prometheus.monitoring.svc.cluster.local:9090"
        prometheus:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
