apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-inference-workload
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ganesh-patrana/gitops-platform-engineering.git'
    targetRevision: main
    path: workloads
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
